name: Build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v4
        
      - name: setup node
        uses: actions/setup-node@v4.0.2
        with:
          node-version: 20

      - name: Install dependencies
        run: yarn install

      - name: Build
        run: yarn build

      - name: Prepublish
        run: yarn prepublish

